### ISSUE TITLE
Wiring up the functionalities with front-end.

### ISSUE THREAD

**Issue by VenkatVenkatesh** [DashboardHub/TribeDashboard#24]
#2

**Comment by eddiejaoude** [comment]
The title is not clear, wiring up what with what?

Rather than doing lots of backend and separately lots of frontend, it would be more beneficial for the user if we can do vertical slices. When one functionality of the backend is done, that is wired up as part of that story instead of separating the.

**Comment by VenkatVenkatesh** [comment]
Closed the issue as the story is not needed.
